### ISSUE TITLE
Add README

### ISSUE THREAD

**Issue by Fasten90** [Fasten90/FastenDocSystem#3]

**Comment by Fasten90** [comment]
> 
> 
> Any guidance regarding what to put in the README file?

Hi!

I think a summary (goal, restrictions) and how-to-use shall be described in the README :)
I will try to do it in the next weeks.

Are you interested in this project?

**Comment by C-Lion** [comment]
Where can I find this information? Your url says  www.fasten.e5tv.hu’s server IP address could not be found so I have no idea what this tool/repo is for. I was sent to the repo because you have open documentation issues & I like to work on documentation in MD files as part of Hacktoberfest.

**Comment by Fasten90** [comment]
Dear @C-Lion ,
Unfortunately, the most of information is in my head. This project was a prototype/test project, and I tried to:
- Using reportlab as pdf generation
- export md/csv table data to pdf

Maybe I will start it with a code reading, and collecting the actual knownledge of the script.
You can leave as is, or please try to summary by actual code status. I am sorry.

Best Regards,

**Comment by C-Lion** [comment]
Thanks. Looks good to me. Lets give it time & see if it updates. Thanks so much & good luck with this.
